// AUTO-GENERATED by catalog-gen ax-plotting — do not edit manually
import type { Completion } from "@codemirror/autocomplete";
import { snippet } from "@codemirror/autocomplete";

export const DRAW_OBJECTS_2D: Completion[] = [
  {
    label: "explicit",
    detail: "explicit(expr, var, lo, hi)",
    info: "A curve y = f(x)",
    type: "function",
    apply: snippet("explicit(${1:expr}, ${2:var}, ${3:lo}, ${4:hi})"),
    boost: 10,
  },
  {
    label: "parametric",
    detail: "parametric(xexpr, yexpr, tvar, tlo, thi)",
    info: "A parametric curve",
    type: "function",
    apply: snippet("parametric(${1:xexpr}, ${2:yexpr}, ${3:t}, ${4:tlo}, ${5:thi})"),
    boost: 9,
  },
  {
    label: "points",
    detail: "points(data)",
    info: "Scatter points [[x1,y1],[x2,y2],...]",
    type: "function",
    apply: snippet("points(${1:data})"),
    boost: 8,
  },
  {
    label: "implicit",
    detail: "implicit(eqn, xvar, xlo, xhi, yvar, ylo, yhi)",
    info: "An implicit curve f(x,y) = 0",
    type: "function",
    apply: snippet("implicit(${1:eqn}, ${2:x}, ${3:xlo}, ${4:xhi}, ${5:y}, ${6:ylo}, ${7:yhi})"),
    boost: 7,
  },
  {
    label: "ax_contour",
    detail: "ax_contour(expr, xvar, xlo, xhi, yvar, ylo, yhi)",
    info: "Filled contour plot of f(x,y)",
    type: "function",
    apply: snippet("ax_contour(${1:expr}, ${2:x}, ${3:xlo}, ${4:xhi}, ${5:y}, ${6:ylo}, ${7:yhi})"),
    boost: 6,
  },
  {
    label: "ax_heatmap",
    detail: "ax_heatmap(z_matrix) or ax_heatmap(expr, x, xlo, xhi, y, ylo, yhi)",
    info: "Heatmap from matrix or expression",
    type: "function",
    apply: snippet("ax_heatmap(${1:data})"),
    boost: 5,
  },
  {
    label: "ax_bar",
    detail: "ax_bar(categories, values)",
    info: "Bar chart",
    type: "function",
    apply: snippet("ax_bar(${1:categories}, ${2:values})"),
    boost: 4,
  },
  {
    label: "ax_histogram",
    detail: "ax_histogram(data)",
    info: "Histogram of numeric data",
    type: "function",
    apply: snippet("ax_histogram(${1:data})"),
    boost: 3,
  },
];

export const DRAW_OBJECTS_3D: Completion[] = [
  {
    label: "explicit",
    detail: "explicit(expr, xvar, xlo, xhi, yvar, ylo, yhi)",
    info: "A surface z = f(x,y)",
    type: "function",
    apply: snippet("explicit(${1:expr}, ${2:x}, ${3:xlo}, ${4:xhi}, ${5:y}, ${6:ylo}, ${7:yhi})"),
    boost: 10,
  },
  {
    label: "points",
    detail: "points(data)",
    info: "3D scatter points [[x1,y1,z1],...]",
    type: "function",
    apply: snippet("points(${1:data})"),
    boost: 9,
  },
];

export const STYLE_OPTIONS: Completion[] = [
  { label: "color", detail: "Trace color", type: "property", apply: "color=", boost: 10 },
  { label: "line_width", detail: "Line width in pixels", type: "property", apply: "line_width=", boost: 9 },
  { label: "dash", detail: "\"solid\", \"dot\", \"dash\", \"dashdot\"", type: "property", apply: "dash=", boost: 8 },
  { label: "opacity", detail: "Trace opacity (0–1)", type: "property", apply: "opacity=", boost: 7 },
  { label: "name", detail: "Legend entry", type: "property", apply: "name=", boost: 6 },
  { label: "fill", detail: "\"tozeroy\", \"toself\", etc.", type: "property", apply: "fill=", boost: 5 },
  { label: "marker_symbol", detail: "\"circle\", \"diamond\", \"square\"", type: "property", apply: "marker_symbol=", boost: 4 },
  { label: "marker_size", detail: "Marker size", type: "property", apply: "marker_size=", boost: 3 },
  { label: "fill_color", detail: "Fill color", type: "property", apply: "fill_color=", boost: 2 },
  { label: "colorscale", detail: "\"Viridis\", \"Hot\", \"Blues\", etc.", type: "property", apply: "colorscale=", boost: 1 },
  { label: "nticks", detail: "Sampling resolution", type: "property", apply: "nticks=" },
  { label: "showscale", detail: "Show colorbar (true/false)", type: "property", apply: "showscale=" },
  { label: "ncontours", detail: "Number of contour levels", type: "property", apply: "ncontours=" },
  { label: "nbins", detail: "Number of histogram bins", type: "property", apply: "nbins=" },
  { label: "bar_width", detail: "Bar width fraction", type: "property", apply: "bar_width=" },
];

export const LAYOUT_OPTIONS_2D: Completion[] = [
  { label: "title", detail: "Plot title", type: "property", apply: "title=", boost: 10 },
  { label: "xlabel", detail: "X axis label", type: "property", apply: "xlabel=", boost: 9 },
  { label: "ylabel", detail: "Y axis label", type: "property", apply: "ylabel=", boost: 8 },
  { label: "xrange", detail: "X axis range [lo,hi]", type: "property", apply: "xrange=", boost: 7 },
  { label: "yrange", detail: "Y axis range [lo,hi]", type: "property", apply: "yrange=", boost: 6 },
  { label: "grid", detail: "Show grid (true/false)", type: "property", apply: "grid=" },
  { label: "showlegend", detail: "Show legend (true/false)", type: "property", apply: "showlegend=" },
  { label: "aspect_ratio", detail: "Lock aspect ratio", type: "property", apply: "aspect_ratio=" },
  { label: "width", detail: "Fixed width in pixels", type: "property", apply: "width=" },
  { label: "height", detail: "Fixed height in pixels", type: "property", apply: "height=" },
  { label: "bar_mode", detail: "\"group\", \"stack\", \"overlay\"", type: "property", apply: "bar_mode=", boost: -1 },
];

export const LAYOUT_OPTIONS_3D: Completion[] = [
  { label: "title", detail: "Plot title", type: "property", apply: "title=", boost: 10 },
  { label: "xlabel", detail: "X axis label", type: "property", apply: "xlabel=", boost: 9 },
  { label: "ylabel", detail: "Y axis label", type: "property", apply: "ylabel=", boost: 8 },
  { label: "zlabel", detail: "Z axis label", type: "property", apply: "zlabel=", boost: 7 },
  { label: "xrange", detail: "X axis range", type: "property", apply: "xrange=" },
  { label: "yrange", detail: "Y axis range", type: "property", apply: "yrange=" },
  { label: "zrange", detail: "Z axis range", type: "property", apply: "zrange=" },
  { label: "showlegend", detail: "Show legend (true/false)", type: "property", apply: "showlegend=" },
  { label: "width", detail: "Fixed width in pixels", type: "property", apply: "width=" },
  { label: "height", detail: "Fixed height in pixels", type: "property", apply: "height=" },
];

export const LAYOUT_OPTIONS_POLAR: Completion[] = [
  { label: "title", detail: "Plot title", type: "property", apply: "title=", boost: 10 },
  { label: "showlegend", detail: "Show legend (true/false)", type: "property", apply: "showlegend=" },
  { label: "width", detail: "Fixed width in pixels", type: "property", apply: "width=" },
  { label: "height", detail: "Fixed height in pixels", type: "property", apply: "height=" },
];

export const DRAW_CONTEXT_FUNCTIONS: Record<string, { objects: Completion[]; layout: Completion[] }> = {
  ax_draw2d: { objects: DRAW_OBJECTS_2D, layout: LAYOUT_OPTIONS_2D },
  ax_draw3d: { objects: DRAW_OBJECTS_3D, layout: LAYOUT_OPTIONS_3D },
  ax_plot2d: { objects: [], layout: LAYOUT_OPTIONS_2D },
  ax_polar: { objects: [], layout: LAYOUT_OPTIONS_POLAR },
};
