//! Generate ax_plotting catalog, docs, and TypeScript completions from a single
//! source-of-truth JSON file (`ax_draw_context.json`).

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use serde::Deserialize;

use aximar_core::catalog::types::{FunctionCategory, FunctionExample, MaximaFunction, PackageInfo};

// --- Deserialization types for ax_draw_context.json ---

#[derive(Deserialize)]
pub struct DrawContext {
    pub functions: BTreeMap<String, FunctionDef>,
    pub draw_objects: BTreeMap<String, Vec<DrawObject>>,
    pub style_options: Vec<OptionDef>,
    pub layout_options: BTreeMap<String, Vec<OptionDef>>,
}

#[derive(Deserialize)]
pub struct FunctionDef {
    pub signatures: Vec<String>,
    pub description: String,
    pub category: String,
    pub see_also: Vec<String>,
    pub examples: Vec<ExampleDef>,
    pub docs: String,
    #[serde(default)]
    pub accepts_objects: bool,
    pub object_group: Option<String>,
    #[serde(default)]
    pub style_options: bool,
    pub layout_group: Option<String>,
    #[serde(default)]
    pub search_keywords: String,
}

#[derive(Deserialize)]
pub struct ExampleDef {
    pub input: String,
    pub description: Option<String>,
}

#[derive(Deserialize)]
pub struct DrawObject {
    pub name: String,
    pub detail: String,
    pub info: String,
    pub snippet_params: Vec<String>,
    pub boost: Option<i32>,
}

#[derive(Deserialize)]
pub struct OptionDef {
    pub name: String,
    pub detail: String,
    pub boost: Option<i32>,
}

// --- Generation functions ---

pub fn load(path: &Path) -> DrawContext {
    let json = fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("Error reading {}: {e}", path.display());
        std::process::exit(1);
    });
    serde_json::from_str(&json).unwrap_or_else(|e| {
        eprintln!("Error parsing {}: {e}", path.display());
        std::process::exit(1);
    })
}

fn parse_category(s: &str) -> FunctionCategory {
    match s {
        "Plotting" => FunctionCategory::Plotting,
        "Calculus" => FunctionCategory::Calculus,
        "Algebra" => FunctionCategory::Algebra,
        "LinearAlgebra" => FunctionCategory::LinearAlgebra,
        "Simplification" => FunctionCategory::Simplification,
        "Solving" => FunctionCategory::Solving,
        "Trigonometry" => FunctionCategory::Trigonometry,
        "NumberTheory" => FunctionCategory::NumberTheory,
        "Polynomials" => FunctionCategory::Polynomials,
        "Series" => FunctionCategory::Series,
        "Combinatorics" => FunctionCategory::Combinatorics,
        "Programming" => FunctionCategory::Programming,
        "IO" => FunctionCategory::IO,
        _ => FunctionCategory::Other,
    }
}

/// Generate the catalog entries (`ax_plotting_catalog.json`).
pub fn generate_catalog(ctx: &DrawContext) -> Vec<MaximaFunction> {
    ctx.functions
        .iter()
        .map(|(name, f)| MaximaFunction {
            name: name.clone(),
            signatures: f.signatures.clone(),
            description: f.description.clone(),
            category: parse_category(&f.category),
            examples: f
                .examples
                .iter()
                .map(|e| FunctionExample {
                    input: e.input.clone(),
                    description: e.description.clone(),
                })
                .collect(),
            see_also: f.see_also.clone(),
            search_keywords: f.search_keywords.clone(),
        })
        .collect()
}

/// Generate a `PackageInfo` entry for ax_plotting so these functions
/// appear in the Packages browser alongside Maxima's loadable packages.
pub fn generate_package_info(ctx: &DrawContext) -> PackageInfo {
    let mut functions: Vec<String> = ctx.functions.keys().cloned().collect();
    functions.sort();
    let signatures = ctx
        .functions
        .iter()
        .map(|(name, f)| (name.clone(), f.signatures[0].clone()))
        .collect();
    PackageInfo {
        name: "ax_plotting".to_string(),
        description: "Aximar interactive plotting with Plotly.js — charts, contours, heatmaps, bar charts, histograms, vector fields, and phase portraits".to_string(),
        functions,
        signatures,
        builtin: true,
    }
}

/// Generate the docs map (`ax_plotting_docs.json`).
pub fn generate_docs(ctx: &DrawContext) -> BTreeMap<String, String> {
    ctx.functions
        .iter()
        .map(|(name, f)| (name.clone(), f.docs.clone()))
        .collect()
}

/// Generate TypeScript source for `draw-completions.generated.ts`.
pub fn generate_typescript(ctx: &DrawContext) -> String {
    let mut out = String::new();

    out.push_str(
        "// AUTO-GENERATED by catalog-gen ax-plotting — do not edit manually\n\
         import type { Completion } from \"@codemirror/autocomplete\";\n\
         import { snippet } from \"@codemirror/autocomplete\";\n\n",
    );

    // Draw objects per group
    for (group, objects) in &ctx.draw_objects {
        let const_name = format!("DRAW_OBJECTS_{}", group.to_uppercase());
        out.push_str(&format!(
            "export const {const_name}: Completion[] = [\n"
        ));
        for obj in objects {
            write_draw_object(&mut out, obj);
        }
        out.push_str("];\n\n");
    }

    // Style options
    out.push_str("export const STYLE_OPTIONS: Completion[] = [\n");
    for opt in &ctx.style_options {
        write_option(&mut out, opt);
    }
    out.push_str("];\n\n");

    // Layout options per group
    for (group, opts) in &ctx.layout_options {
        let const_name = format!("LAYOUT_OPTIONS_{}", group.to_uppercase());
        out.push_str(&format!(
            "export const {const_name}: Completion[] = [\n"
        ));
        for opt in opts {
            write_option(&mut out, opt);
        }
        out.push_str("];\n\n");
    }

    // DRAW_CONTEXT_FUNCTIONS map
    out.push_str(
        "export const DRAW_CONTEXT_FUNCTIONS: Record<string, { objects: Completion[]; layout: Completion[] }> = {\n",
    );
    for (name, f) in &ctx.functions {
        // Only include top-level draw/plot functions (those with a layout_group)
        let Some(layout_group) = &f.layout_group else {
            continue;
        };
        let layout_const = format!("LAYOUT_OPTIONS_{}", layout_group.to_uppercase());
        let objects_expr = if f.accepts_objects {
            if let Some(obj_group) = &f.object_group {
                format!("DRAW_OBJECTS_{}", obj_group.to_uppercase())
            } else {
                "[]".to_string()
            }
        } else {
            "[]".to_string()
        };
        out.push_str(&format!(
            "  {name}: {{ objects: {objects_expr}, layout: {layout_const} }},\n"
        ));
    }
    out.push_str("};\n");

    out
}

fn write_draw_object(out: &mut String, obj: &DrawObject) {
    let snippet_args: Vec<String> = obj
        .snippet_params
        .iter()
        .enumerate()
        .map(|(i, p)| format!("${{{}:{}}}", i + 1, p))
        .collect();
    let snippet_str = format!("{}({})", obj.name, snippet_args.join(", "));

    out.push_str("  {\n");
    out.push_str(&format!(
        "    label: {},\n",
        json_string(&obj.name)
    ));
    out.push_str(&format!(
        "    detail: {},\n",
        json_string(&obj.detail)
    ));
    out.push_str(&format!(
        "    info: {},\n",
        json_string(&obj.info)
    ));
    out.push_str("    type: \"function\",\n");
    out.push_str(&format!(
        "    apply: snippet({}),\n",
        json_string(&snippet_str)
    ));
    if let Some(boost) = obj.boost {
        out.push_str(&format!("    boost: {boost},\n"));
    }
    out.push_str("  },\n");
}

fn write_option(out: &mut String, opt: &OptionDef) {
    out.push_str(&format!(
        "  {{ label: {}, detail: {}, type: \"property\", apply: {}",
        json_string(&opt.name),
        json_string(&opt.detail),
        json_string(&format!("{}=", opt.name)),
    ));
    if let Some(boost) = opt.boost {
        out.push_str(&format!(", boost: {boost}"));
    }
    out.push_str(" },\n");
}

/// Produce a JSON-safe double-quoted string literal for embedding in TypeScript.
fn json_string(s: &str) -> String {
    serde_json::to_string(s).expect("failed to serialize string")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_context() -> DrawContext {
        let json = include_str!("../../../crates/aximar-core/src/maxima/ax_draw_context.json");
        serde_json::from_str(json).expect("failed to parse ax_draw_context.json")
    }

    #[test]
    fn catalog_has_all_functions() {
        let ctx = sample_context();
        let catalog = generate_catalog(&ctx);
        assert_eq!(catalog.len(), ctx.functions.len());
        assert!(catalog.iter().any(|f| f.name == "ax_plot2d"));
        assert!(catalog.iter().any(|f| f.name == "ax_draw2d"));
        assert!(catalog.iter().any(|f| f.name == "ax_draw3d"));
        assert!(catalog.iter().any(|f| f.name == "ax_polar"));
        assert!(catalog.iter().any(|f| f.name == "ax_contour"));
        assert!(catalog.iter().any(|f| f.name == "ax_heatmap"));
        assert!(catalog.iter().any(|f| f.name == "ax_bar"));
        assert!(catalog.iter().any(|f| f.name == "ax_histogram"));
        assert!(catalog.iter().any(|f| f.name == "ax_vector_field"));
        assert!(catalog.iter().any(|f| f.name == "ax_streamline"));
    }

    #[test]
    fn docs_has_all_functions() {
        let ctx = sample_context();
        let docs = generate_docs(&ctx);
        assert_eq!(docs.len(), ctx.functions.len());
        for name in ctx.functions.keys() {
            assert!(docs.contains_key(name), "missing docs for {name}");
        }
    }

    #[test]
    fn typescript_contains_expected_exports() {
        let ctx = sample_context();
        let ts = generate_typescript(&ctx);
        assert!(ts.contains("export const DRAW_OBJECTS_2D"));
        assert!(ts.contains("export const DRAW_OBJECTS_3D"));
        assert!(ts.contains("export const STYLE_OPTIONS"));
        assert!(ts.contains("export const LAYOUT_OPTIONS_2D"));
        assert!(ts.contains("export const LAYOUT_OPTIONS_3D"));
        assert!(ts.contains("export const LAYOUT_OPTIONS_POLAR"));
        assert!(ts.contains("export const DRAW_CONTEXT_FUNCTIONS"));
        assert!(ts.contains("ax_plot2d:"));
        assert!(ts.contains("ax_draw2d:"));
        assert!(ts.contains("ax_draw3d:"));
        assert!(ts.contains("ax_polar:"));
        // Draw objects that are used only inside ax_draw2d should NOT appear as top-level entries
        assert!(!ts.contains("ax_contour:"));
    }

    #[test]
    fn typescript_snippet_format() {
        let ctx = sample_context();
        let ts = generate_typescript(&ctx);
        // Check that explicit 2D has the right snippet format
        assert!(ts.contains("snippet(\"explicit(${1:expr}, ${2:var}, ${3:lo}, ${4:hi})\")"));
    }

    #[test]
    fn catalog_roundtrips_to_same_schema() {
        let ctx = sample_context();
        let catalog = generate_catalog(&ctx);
        let json = serde_json::to_string_pretty(&catalog).unwrap();
        let roundtrip: Vec<MaximaFunction> = serde_json::from_str(&json).unwrap();
        assert_eq!(roundtrip.len(), catalog.len());
    }
}
