use std::collections::HashMap;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaximaFunction {
    pub name: String,
    pub signatures: Vec<String>,
    pub description: String,
    pub category: FunctionCategory,
    pub examples: Vec<FunctionExample>,
    #[serde(default)]
    pub see_also: Vec<String>,
    /// Pre-computed search keywords for improved discoverability.
    /// Generated by catalog-gen from name parts, category, and manual aliases.
    #[serde(default)]
    pub search_keywords: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionExample {
    pub input: String,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FunctionCategory {
    Calculus,
    Algebra,
    LinearAlgebra,
    Simplification,
    Solving,
    Plotting,
    Trigonometry,
    NumberTheory,
    Polynomials,
    Series,
    Combinatorics,
    Programming,
    IO,
    Other,
}

impl FunctionCategory {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Calculus => "Calculus",
            Self::Algebra => "Algebra",
            Self::LinearAlgebra => "Linear Algebra",
            Self::Simplification => "Simplification",
            Self::Solving => "Solving",
            Self::Plotting => "Plotting",
            Self::Trigonometry => "Trigonometry",
            Self::NumberTheory => "Number Theory",
            Self::Polynomials => "Polynomials",
            Self::Series => "Series",
            Self::Combinatorics => "Combinatorics",
            Self::Programming => "Programming",
            Self::IO => "I/O",
            Self::Other => "Other",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    pub function: MaximaFunction,
    pub score: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResult {
    pub name: String,
    pub signature: String,
    pub description: String,
    pub insert_text: String,
    /// If this function requires a package to be loaded first, the package name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub package: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CategoryGroup {
    pub category: FunctionCategory,
    pub label: String,
    pub functions: Vec<MaximaFunction>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeprecationInfo {
    pub name: String,
    pub description: String,
    pub replacement: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageInfo {
    /// Load path, e.g. "distrib" or "simplification/absimp"
    pub name: String,
    /// Short description of the package
    pub description: String,
    /// Function names provided by this package
    pub functions: Vec<String>,
    /// Function name → signature string, e.g. "pdf_normal" → "pdf_normal(x, m, s)"
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub signatures: HashMap<String, String>,
    /// Built-in packages are auto-loaded and don't need `load("...")$`
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub builtin: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageSearchResult {
    pub package: PackageInfo,
    pub score: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageCompletionResult {
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageFunctionSearchResult {
    pub function_name: String,
    pub package_name: String,
    pub package_description: String,
    pub score: f64,
    #[serde(default)]
    pub signature: String,
}
